-- 코드를 입력하세요
-- SELECT * FROM CAR_RENTAL_COMPANY_CAR ;
 -- SELECT * FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY ;
-- SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN ;

SELECT DISTINCT
    T.CAR_ID
    , T.CAR_TYPE
    , T.FEE
FROM(    
    SELECT 
        CC.CAR_ID
        , CC.CAR_TYPE
        -- , CC.DAILY_FEE
        -- , DP.DISCOUNT_RATE
        , (CC.DAILY_FEE * 30) * ((100 - DP.DISCOUNT_RATE) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY RH
    INNER JOIN CAR_RENTAL_COMPANY_CAR CC
    ON RH.CAR_ID = CC.CAR_ID
        AND (CC.CAR_TYPE = 'SUV'
        OR CC.CAR_TYPE = '세단')
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN DP
    ON CC.CAR_TYPE = DP.CAR_TYPE
        AND DP.DURATION_TYPE = '30일 이상'
    WHERE RH.CAR_ID NOT IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= DATE '2022-11-30'
            AND END_DATE >= DATE '2022-11-01'
    )
) T
WHERE T.FEE >= 500000
    AND T.FEE < 2000000
ORDER BY T.FEE DESC, T.CAR_TYPE ASC, T.CAR_ID DESC