
    
SELECT 
    TEMP.FOOD_TYPE
    , RI.REST_ID
    , RI.REST_NAME
    , TEMP.FAVORITES
FROM (
    SELECT
    MAX(FAVORITES) AS FAVORITES
    , FOOD_TYPE
    FROM REST_INFO
    GROUP BY FOOD_TYPE
   ) TEMP
INNER JOIN REST_INFO RI
ON RI.FOOD_TYPE = TEMP.FOOD_TYPE
    AND RI.FAVORITES = TEMP.FAVORITES
 ORDER BY RI.FOOD_TYPE DESC    
    