-- 코드를 입력하세요
SELECT 
    EXTRACT(YEAR FROM OS.SALES_DATE) AS YEAR
    , EXTRACT(MONTH FROM OS.SALES_DATE) AS MONTH
    , UI.GENDER
    , COUNT(DISTINCT OS.USER_ID) AS USERS
FROM ONLINE_SALE OS
INNER JOIN USER_INFO  UI
ON OS.USER_ID = UI.USER_ID
WHERE UI.GENDER IS NOT NULL
GROUP BY EXTRACT(YEAR FROM OS.SALES_DATE), EXTRACT(MONTH FROM OS.SALES_DATE), UI.GENDER
ORDER BY YEAR,MONTH,UI.GENDER