-- 코드를 입력하세요
SELECT
    CAR_ID
    ,CASE WHEN MAX(AVAILABILITY) = 1
        THEN '대여중'
        ELSE '대여 가능'
        END AS AVAILABILITY
FROM
(SELECT
    CAR_ID
    , CASE WHEN TO_DATE('2022-10-16','YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
        THEN 1
        ELSE 0
        END AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY)
GROUP BY CAR_ID
ORDER BY CAR_ID DESC


-- SELECT
--     CAR_ID
--     ,START_DATE
--     ,END_DATE
--     , CASE WHEN TO_DATE('2022-10-16','YYYY-MM-DD') BETWEEN START_DATE AND END_DATE
--         THEN '대여중'
--         ELSE '대여가능'
--         END AS AVAILABILITY
-- FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
-- ORDER BY CAR_ID