SELECT
    T.PRODUCT_ID
    , T.PRODUCT_NAME
    , T.TOTLA_SALSES
FROM(
    SELECT
        FO.PRODUCT_ID
        , MAX(FP.PRODUCT_NAME) AS PRODUCT_NAME
        , SUM(FO.AMOUNT * FP.PRICE) AS TOTLA_SALSES        
    FROM FOOD_ORDER FO
    INNER JOIN FOOD_PRODUCT FP
    ON FO.PRODUCT_ID = FP.PRODUCT_ID
    WHERE FO.PRODUCE_DATE >= DATE '2022-05-01'
        AND FO.PRODUCE_DATE < DATE '2022-06-01'    
    GROUP BY FO.PRODUCT_ID
) T
ORDER BY TOTLA_SALSES DESC, PRODUCT_ID ASC