-- 코드를 입력하세요
SELECT 
    O.HOUR
    , NVL(T.COUNT, 0) AS COUNT
FROM(
 SELECT LEVEL - 1 AS HOUR
  FROM dual
  CONNECT BY LEVEL <= 24
)O
LEFT OUTER JOIN(
    SELECT
     TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) AS HOUR
     , COUNT(*) AS COUNT
    FROM ANIMAL_OUTS 
    GROUP BY TO_CHAR(DATETIME, 'HH24')
)T
ON T.HOUR = O.HOUR
ORDER BY HOUR

