-- 코드를 입력하세요
-- SELECT * FROM FOOD_PRODUCT ;

-- SELECT 
--     CATEGORY
--     , MAX(PRICE) AS MAX_PRICE
-- FROM FOOD_PRODUCT 
-- WHERE CATEGORY IN('과자', '국', '김치','식용유')
-- GROUP BY CATEGORY
-- ORDER BY MAX_PRICE DESC


SELECT 
    FP.CATEGORY
    , TEMP.MP AS MAX_PRICE
    , FP.PRODUCT_NAME
FROM FOOD_PRODUCT FP
INNER JOIN(
    SELECT 
        CATEGORY
        , MAX(PRICE) AS MP
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN('과자', '국', '김치','식용유')
    GROUP BY CATEGORY
)TEMP
ON TEMP.CATEGORY = FP.CATEGORY
    AND TEMP.MP = FP.PRICE
WHERE FP.CATEGORY IN('과자', '국', '김치','식용유')
ORDER BY TEMP.MP DESC